# Generated by Django 3.0 on 2020-03-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200321_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='imagecheck',
            new_name='image',
        ),
    ]
